BEGIN;
CREATE SEQUENCE "dom"."account_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "dom"."Account"."Id";
CREATE SEQUENCE "dom"."application_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "dom"."Application"."Id";
CREATE SEQUENCE "dom"."emailrequest_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "dom"."EmailRequest"."Id";
CREATE SEQUENCE "dom"."environment_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "dom"."Environment"."Id";
CREATE SEQUENCE "dom"."message_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "dom"."Message"."Id";
CREATE SEQUENCE "dom"."permission_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "dom"."Permission"."Id";
CREATE SEQUENCE "dom"."role_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "dom"."Role"."Id";
CREATE SEQUENCE "dom"."smsrequest_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "dom"."SmsRequest"."Id";
CREATE SEQUENCE "dom"."tokenregistration_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "dom"."TokenRegistration"."Id";
ALTER TABLE "dom"."Account" ADD CONSTRAINT "PK_Account_Id" PRIMARY KEY ("Id");
ALTER TABLE "dom"."AccountEnvironment" ADD CONSTRAINT "PK_dom_AccountEnvironment" PRIMARY KEY ("EnvironmentId","UserId");
ALTER TABLE "dom"."Application" ADD CONSTRAINT "PK_dom_Application" PRIMARY KEY ("Id");
ALTER TABLE "dom"."EmailRequest" ADD CONSTRAINT "PK_EmailRequest_Id" PRIMARY KEY ("Id");
ALTER TABLE "dom"."Environment" ADD CONSTRAINT "PK_dom_Environment" PRIMARY KEY ("Id");
ALTER TABLE "dom"."Message" ADD CONSTRAINT "PK_Message_Id" PRIMARY KEY ("Id");
ALTER TABLE "dom"."Permission" ADD CONSTRAINT "PK_dom_Permission" PRIMARY KEY ("Id");
ALTER TABLE "dom"."PermissionRole" ADD CONSTRAINT "PK_dom_PermissionRole" PRIMARY KEY ("PermissionId","RoleId");
ALTER TABLE "dom"."PermissionUser" ADD CONSTRAINT "PK_dom_PermissionUser" PRIMARY KEY ("PermissionId","UserId");
ALTER TABLE "dom"."Role" ADD CONSTRAINT "PK_dom_Role" PRIMARY KEY ("Id");
ALTER TABLE "dom"."RoleUser" ADD CONSTRAINT "PK_dom_RoleUser" PRIMARY KEY ("RoleId","UserId");
ALTER TABLE "dom"."SmsRequest" ADD CONSTRAINT "PK_SmsRequest_Id" PRIMARY KEY ("Id");
ALTER TABLE "dom"."TokenRegistration" ADD CONSTRAINT "PK_TokenRegistration_Id" PRIMARY KEY ("Id");
CREATE SEQUENCE "hst_dom"."account_h_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "hst_dom"."Account"."H_ID";
CREATE SEQUENCE "hst_dom"."application_h_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "hst_dom"."Application"."H_ID";
CREATE SEQUENCE "hst_dom"."emailrequest_h_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "hst_dom"."EmailRequest"."H_ID";
CREATE SEQUENCE "hst_dom"."message_h_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "hst_dom"."Message"."H_ID";
CREATE SEQUENCE "hst_dom"."permission_h_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "hst_dom"."Permission"."H_ID";
CREATE SEQUENCE "hst_dom"."permissionrole_h_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "hst_dom"."PermissionRole"."H_ID";
CREATE SEQUENCE "hst_dom"."permissionuser_h_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "hst_dom"."PermissionUser"."H_ID";
CREATE SEQUENCE "hst_dom"."role_h_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "hst_dom"."Role"."H_ID";
CREATE SEQUENCE "hst_dom"."roleuser_h_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "hst_dom"."RoleUser"."H_ID";
CREATE SEQUENCE "hst_dom"."smsrequest_h_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "hst_dom"."SmsRequest"."H_ID";
CREATE SEQUENCE "hst_dom"."tokenregistration_h_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "hst_dom"."TokenRegistration"."H_ID";
ALTER TABLE "hst_dom"."Account" ADD CONSTRAINT "PK_Account_History" PRIMARY KEY ("H_ID");
ALTER TABLE "hst_dom"."Application" ADD CONSTRAINT "PK_Application_History" PRIMARY KEY ("H_ID");
ALTER TABLE "hst_dom"."EmailRequest" ADD CONSTRAINT "PK_EmailRequest_History" PRIMARY KEY ("H_ID");
ALTER TABLE "hst_dom"."Message" ADD CONSTRAINT "PK_Message_History" PRIMARY KEY ("H_ID");
ALTER TABLE "hst_dom"."Permission" ADD CONSTRAINT "PK_Permission_History" PRIMARY KEY ("H_ID");
ALTER TABLE "hst_dom"."PermissionRole" ADD CONSTRAINT "PK_PermissionRole_History" PRIMARY KEY ("H_ID");
ALTER TABLE "hst_dom"."PermissionUser" ADD CONSTRAINT "PK_PermissionUser_History" PRIMARY KEY ("H_ID");
ALTER TABLE "hst_dom"."Role" ADD CONSTRAINT "PK_Role_History" PRIMARY KEY ("H_ID");
ALTER TABLE "hst_dom"."RoleUser" ADD CONSTRAINT "PK_RoleUser_History" PRIMARY KEY ("H_ID");
ALTER TABLE "hst_dom"."SmsRequest" ADD CONSTRAINT "PK_SmsRequest_History" PRIMARY KEY ("H_ID");
ALTER TABLE "hst_dom"."TokenRegistration" ADD CONSTRAINT "PK_TokenRegistration_History" PRIMARY KEY ("H_ID");
CREATE SEQUENCE "log"."access_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "log"."Access"."Id";
ALTER TABLE "log"."Access" ADD CONSTRAINT "PK_log_Access_Id" PRIMARY KEY ("Id");
ALTER TABLE "dom"."Permission" ADD CONSTRAINT "UQ_dom_Permission" UNIQUE ("Name");
ALTER TABLE "dom"."Role" ADD CONSTRAINT "UQ_dom_Role" UNIQUE ("Name");
CREATE INDEX "IX_Account_Email" ON "dom"."Account" ("Email" ASC);
CREATE INDEX "IX_Account_Login" ON "dom"."Account" ("Login" ASC);
CREATE INDEX "IX_Account_Phone" ON "dom"."Account" ("Phone" ASC);
CREATE INDEX "IX_EmailRequest_Email_ExpiredAt" ON "dom"."EmailRequest" ("Email" ASC,"ExpiredAt" DESC);
CREATE INDEX "IX_EmailRequest_UserId_ExpiredAt" ON "dom"."EmailRequest" ("UserId" ASC,"ExpiredAt" DESC);
CREATE UNIQUE INDEX "IX_Environment_Token" ON "dom"."Environment" ("Token" ASC);
CREATE INDEX "IX_Message_Name_Type_Locale" ON "dom"."Message" ("Name" ASC,"Type" ASC,"Locale" ASC);
CREATE INDEX "IX_Permission_Name" ON "dom"."Permission" ("Name" ASC);
CREATE INDEX "IX_Role_Name" ON "dom"."Role" ("Name" ASC);
CREATE INDEX "IX_RoleUser_UserId" ON "dom"."RoleUser" ("UserId" ASC);
CREATE INDEX "IX_SmsRequest_Phone_ExpiredAt" ON "dom"."SmsRequest" ("Phone" ASC,"ExpiredAt" DESC);
CREATE INDEX "IX_SmsRequest_UserId_ExpiredAt" ON "dom"."SmsRequest" ("UserId" ASC,"ExpiredAt" DESC);
ALTER TABLE "dom"."AccountEnvironment" ADD CONSTRAINT "FK_dom_AccountEnvironment_UserId" FOREIGN KEY ("UserId") REFERENCES "dom"."Account" ( "Id") ON DELETE CASCADE;
ALTER TABLE "dom"."AccountEnvironment" ADD CONSTRAINT "PK_dom_AccountEnvironment_Id" FOREIGN KEY ("EnvironmentId") REFERENCES "dom"."Environment" ( "Id");
ALTER TABLE "dom"."Permission" ADD CONSTRAINT "FK_dom_Permission_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES "dom"."Application" ( "Id");
ALTER TABLE "dom"."PermissionRole" ADD CONSTRAINT "FK_dom_PermissionRole_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "dom"."Permission" ( "Id");
ALTER TABLE "dom"."PermissionRole" ADD CONSTRAINT "FK_dom_PermissionRole_RoleId" FOREIGN KEY ("RoleId") REFERENCES "dom"."Role" ( "Id");
ALTER TABLE "dom"."PermissionUser" ADD CONSTRAINT "FK_dom_PermissionUser_UserId" FOREIGN KEY ("UserId") REFERENCES "dom"."Account" ( "Id") ON DELETE CASCADE;
ALTER TABLE "dom"."RoleUser" ADD CONSTRAINT "FK_dom_RoleUser_RoleId" FOREIGN KEY ("RoleId") REFERENCES "dom"."Role" ( "Id");
ALTER TABLE "dom"."RoleUser" ADD CONSTRAINT "FK_dom_RoleUser_UserId" FOREIGN KEY ("UserId") REFERENCES "dom"."Account" ( "Id") ON DELETE CASCADE;
ALTER TABLE "dom"."Account" ALTER COLUMN "Id" SET DEFAULT nextval('"dom"."account_id_seq"');
ALTER TABLE "dom"."Account" ALTER COLUMN "IsLocked" SET DEFAULT false;
ALTER TABLE "dom"."Application" ALTER COLUMN "Id" SET DEFAULT nextval('"dom"."application_id_seq"');
ALTER TABLE "dom"."EmailRequest" ALTER COLUMN "Id" SET DEFAULT nextval('"dom"."emailrequest_id_seq"');
ALTER TABLE "dom"."Environment" ALTER COLUMN "Id" SET DEFAULT nextval('"dom"."environment_id_seq"');
ALTER TABLE "dom"."Environment" ALTER COLUMN "IsDefault" SET DEFAULT false;
ALTER TABLE "dom"."Message" ALTER COLUMN "Id" SET DEFAULT nextval('"dom"."message_id_seq"');
ALTER TABLE "dom"."Permission" ALTER COLUMN "Id" SET DEFAULT nextval('"dom"."permission_id_seq"');
ALTER TABLE "dom"."Role" ALTER COLUMN "Id" SET DEFAULT nextval('"dom"."role_id_seq"');
ALTER TABLE "dom"."Role" ALTER COLUMN "IsDefault" SET DEFAULT false;
ALTER TABLE "dom"."SmsRequest" ALTER COLUMN "Id" SET DEFAULT nextval('"dom"."smsrequest_id_seq"');
ALTER TABLE "dom"."TokenRegistration" ALTER COLUMN "Id" SET DEFAULT nextval('"dom"."tokenregistration_id_seq"');
ALTER TABLE "hst_dom"."Account" ALTER COLUMN "H_ID" SET DEFAULT nextval('"hst_dom"."account_h_id_seq"');
ALTER TABLE "hst_dom"."Application" ALTER COLUMN "H_ID" SET DEFAULT nextval('"hst_dom"."application_h_id_seq"');
ALTER TABLE "hst_dom"."EmailRequest" ALTER COLUMN "H_ID" SET DEFAULT nextval('"hst_dom"."emailrequest_h_id_seq"');
ALTER TABLE "hst_dom"."Message" ALTER COLUMN "H_ID" SET DEFAULT nextval('"hst_dom"."message_h_id_seq"');
ALTER TABLE "hst_dom"."Permission" ALTER COLUMN "H_ID" SET DEFAULT nextval('"hst_dom"."permission_h_id_seq"');
ALTER TABLE "hst_dom"."PermissionRole" ALTER COLUMN "H_ID" SET DEFAULT nextval('"hst_dom"."permissionrole_h_id_seq"');
ALTER TABLE "hst_dom"."PermissionUser" ALTER COLUMN "H_ID" SET DEFAULT nextval('"hst_dom"."permissionuser_h_id_seq"');
ALTER TABLE "hst_dom"."Role" ALTER COLUMN "H_ID" SET DEFAULT nextval('"hst_dom"."role_h_id_seq"');
ALTER TABLE "hst_dom"."RoleUser" ALTER COLUMN "H_ID" SET DEFAULT nextval('"hst_dom"."roleuser_h_id_seq"');
ALTER TABLE "hst_dom"."SmsRequest" ALTER COLUMN "H_ID" SET DEFAULT nextval('"hst_dom"."smsrequest_h_id_seq"');
ALTER TABLE "hst_dom"."TokenRegistration" ALTER COLUMN "H_ID" SET DEFAULT nextval('"hst_dom"."tokenregistration_h_id_seq"');
ALTER TABLE "log"."Access" ALTER COLUMN "Id" SET DEFAULT nextval('"log"."access_id_seq"');
select setval('"dom"."account_id_seq"',(select max("Id") from "dom"."Account")::bigint);
select setval('"dom"."application_id_seq"',(select max("Id") from "dom"."Application")::bigint);
select setval('"dom"."emailrequest_id_seq"',(select max("Id") from "dom"."EmailRequest")::bigint);
select setval('"dom"."environment_id_seq"',(select max("Id") from "dom"."Environment")::bigint);
select setval('"dom"."message_id_seq"',(select max("Id") from "dom"."Message")::bigint);
select setval('"dom"."permission_id_seq"',(select max("Id") from "dom"."Permission")::bigint);
select setval('"dom"."role_id_seq"',(select max("Id") from "dom"."Role")::bigint);
select setval('"dom"."smsrequest_id_seq"',(select max("Id") from "dom"."SmsRequest")::bigint);
select setval('"dom"."tokenregistration_id_seq"',(select max("Id") from "dom"."TokenRegistration")::bigint);
select setval('"hst_dom"."account_h_id_seq"',(select max("H_ID") from "hst_dom"."Account")::bigint);
select setval('"hst_dom"."application_h_id_seq"',(select max("H_ID") from "hst_dom"."Application")::bigint);
select setval('"hst_dom"."emailrequest_h_id_seq"',(select max("H_ID") from "hst_dom"."EmailRequest")::bigint);
select setval('"hst_dom"."message_h_id_seq"',(select max("H_ID") from "hst_dom"."Message")::bigint);
select setval('"hst_dom"."permission_h_id_seq"',(select max("H_ID") from "hst_dom"."Permission")::bigint);
select setval('"hst_dom"."permissionrole_h_id_seq"',(select max("H_ID") from "hst_dom"."PermissionRole")::bigint);
select setval('"hst_dom"."permissionuser_h_id_seq"',(select max("H_ID") from "hst_dom"."PermissionUser")::bigint);
select setval('"hst_dom"."role_h_id_seq"',(select max("H_ID") from "hst_dom"."Role")::bigint);
select setval('"hst_dom"."roleuser_h_id_seq"',(select max("H_ID") from "hst_dom"."RoleUser")::bigint);
select setval('"hst_dom"."smsrequest_h_id_seq"',(select max("H_ID") from "hst_dom"."SmsRequest")::bigint);
select setval('"hst_dom"."tokenregistration_h_id_seq"',(select max("H_ID") from "hst_dom"."TokenRegistration")::bigint);
select setval('"log"."access_id_seq"',(select max("Id") from "log"."Access")::bigint);
COMMIT;
